import type { Metadata } from "next";
import { Inter, Open_Sans, Poppins } from "next/font/google";
import "../styles/global.css";
import ScrollToTop from "@/components/common/ScrollToTop";
import Footer from "@/components/layouts/Footer";
import Decorators from "@/components/ui/decorators";
import { Toaster } from "react-hot-toast";
const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });
const open_sans = Open_Sans({ subsets: ["latin"], variable: "--font-inter" });
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "600", "700"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Porfolio",
  description: "Generated by MTIT",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${poppins.variable} ${open_sans.variable} antialiased`}
      >
        <Toaster
          position="top-right"
          reverseOrder={false}
          toastOptions={{
            style: {
              borderRadius: "16px",
              padding: "14px 20px",
              fontSize: "15px",
              fontWeight: 600,
              boxShadow: "0 10px 30px rgba(0,0,0,0.08)",
              minWidth: "280px",
            },
            success: {
              style: {
                background: "#f0fdf4",
                color: "#22c55e",
                border: "1px solid #4ade80",
              },

              iconTheme: {
                primary: "#22c55e",
                secondary: "#f0fdf4",
              },
            },
          }}
        />
        <Decorators />
        <ScrollToTop />
        {children}
        <Footer />
      </body>
    </html>
  );
}
